# Generated by Django 2.2.7 on 2020-04-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20200418_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsmodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
